FROM ghcr.io/deamen/cifs/coss9-base:latest
LABEL maintainer="Song Tang"

LABEL name="cifs/coss9-minimal"
LABEL version="9.0.0"

RUN dnf update -y --nodocs --setopt install_weak_deps=False && \
    dnf clean all

CMD ["/bin/bash"]

RUN rm -rf /var/log/*
