FROM scratch AS builder
LABEL maintainer="Song Tang"

ADD layer.tar /

FROM builder
LABEL maintainer="Song Tang"

RUN dnf update -y --nodocs --setopt install_weak_deps=False && \
    dnf clean all

RUN rm -rf /var/log/*

