FROM ghcr.io/deamen/cifs/alma9-base:latest
LABEL maintainer="Song Tang"

LABEL name="cifs/alma9-minimal"

RUN microdnf update -y --nodocs --setopt install_weak_deps=0 && \
    microdnf clean all

CMD ["/bin/bash"]

RUN rm -rf /var/log/*
