FROM ghcr.io/deamen/cifs/rocky8-base:latest
LABEL maintainer="Song Tang"

LABEL name="cifs/rocky8-minimal"

RUN microdnf update -y --nodocs --setopt install_weak_deps=False && \
    microdnf clean all

CMD ["/bin/bash"]

RUN rm -rf /var/log/*
