FROM ghcr.io/deamen/cifs/fedora36-base:latest
LABEL maintainer="Song Tang"

LABEL name="cifs/fedora36-init"

RUN microdnf install -y systemd procps-ng --nodocs --setopt install_weak_deps=0 && \
    microdnf clean all

CMD ["/sbin/init"]

STOPSIGNAL SIGRTMIN+3

RUN systemctl mask systemd-remount-fs.service dev-hugepages.mount sys-fs-fuse-connections.mount systemd-logind.service getty.target console-getty.service systemd-udev-trigger.service systemd-udevd.service systemd-random-seed.service
