FROM docker.io/library/debian:bullseye-slim AS builder
RUN mkdir /rootfs/
RUN apt-get update && \
    apt-get install -y debootstrap
RUN debootstrap --force-check-gpg \
                --variant=minbase \
                --components=main \
                bullseye /rootfs/
RUN rm -rf /rootfs/var/cache/apt/archives/*

FROM scratch

COPY --from=builder /rootfs/ /
