name: "CIFS: alma9"

on:
  push:
    branches: [ "master" ]
    paths: 
       - 'alma9/**'
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-alma9-base-image:
    uses: ./.github/workflows/cifs_base_workflow.yml
    with:
      distro: alma9
      registry: ghcr.io

  build-alma9-init-and-minimal-image:
    needs: [build-alma9-base-image]
    uses: ./.github/workflows/cifs_non_base_workflow.yml
    with:
      distro: alma9
      registry: ghcr.io
