# This is a basic workflow to help you get started with Actions

name: "CIFS: alpine"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: 
       - 'alpine/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-alpine-base-image:
    uses: ./.github/workflows/fedora_base_workflow.yml
    with:
      distro: alpine
      registry: ghcr.io
      tarball: "alpine-minirootfs-3.16.1-x86_64.tar.gz"
      tarball_uri: "https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64"
      tarball_checksum_uri: "https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64"
      tarball_checksum_file: "alpine-minirootfs-3.16.1-x86_64.tar.gz.sha256"
      tarball_gpg_key: "ncopa.asc"
      tarball_gpg_uri: "https://alpinelinux.org/keys"
      tarball_signature: "alpine-minirootfs-3.16.1-x86_64.tar.gz.asc"
      tarball_signature_uri: "https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64"
 
  build-alpine-init-and-minimal-image:
    needs: [build-alpine-base-image]
    uses: ./.github/workflows/cifs_non_base_workflow.yml
    with:
      distro: alpine
      registry: ghcr.io
