name: Alpine image workflow

on:
  push:
    branches:
      - master
    paths:
      - 'alpine/**'
  pull_request:
    branches:
      - master
    paths:
      - 'alpine/**'

jobs:
  build-push-base-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    env:
      ALPINE_VERSION: 3.21.3
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Run setup-qemu-static action
        uses: deamen/gh-actions/setup-qemu-static@master
        with:
          targets: 'aarch64'

      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah qemu-user-static

      - name: Build Alpine base image
        run: |
          ARCH=${{ matrix.arch }} ./alpine/buildah_alpine-base.sh

      - name: Log in to the Container registry with buildah
        run: |
          buildah login \
          --username ${{ vars.REGISTRY_USERNAME }} \
          --password ${{ secrets.REGISTRY_PASSWORD }} \
          ${{ vars.REGISTRY_SERVER }}

      - name: Create and push multi-arch manifest
        run: |
          ./alpine/buildah_multiarch.sh quay.io/deamen/alpine-base
