name: CIFS non-base workflow

on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string
      registry:
        required: true
        type: string
        
jobs:
 
  build-scan-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - init
          - minimal
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container image
        run: docker build ./${{ inputs.distro }}/ --file ./${{ inputs.distro }}/Dockerfile.${{ inputs.distro }}-${{ matrix.type }} --tag ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.distro }}-${{ matrix.type }}:${{ github.run_id }}

      - name: Run the Anchore scan
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "${{ inputs.registry }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}"
          acs-report-enable: true
          fail-build: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Push the image as is
        run: docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.distro }}-${{ matrix.type }}:${{ github.run_id }}

      - name: Tag image as latest
        run: docker tag ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.distro }}-${{ matrix.type }}:${{ github.run_id }} ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.distro }}-${{ matrix.type }}:latest

      - name: Push the image as latest
        run: docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.distro }}-${{ matrix.type }}:latest
