# This is a basic workflow to help you get started with Actions

name: "CI: fedora"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: 
       - 'fedora/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  UPSTREAM_URI: "https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Container/x86_64/images/Fedora-Container-Minimal-Base-36-1.5.x86_64.tar.xz"
  UPSTREAM_IMAGE: "Fedora-Container-Minimal-Base-36-1.5.x86_64.tar.xz"
  UPSTREAM_CHEKSUM: "https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Container/x86_64/images/Fedora-Container-36-1.5-x86_64-CHECKSUM"
  UPSTREAM_GPG: "https://getfedora.org/static/fedora.gpg"

jobs:
  build-scan-push-base-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - base
    steps:
      - uses: actions/checkout@v3

      - name: Download container tarball
        run: curl -O ${{ env.UPSTREAM_URI }}

      - name: Download CHECKSUM file
        run: curl -O ${{ env.UPSTREAM_CHEKSUM }}
      
      - name: Download gpg file
        run: curl -O ${{ env.UPSTREAM_GPG }}

      - name: Verify the CHECKSUM file
        run: gpgv --keyring ./fedora.gpg *-CHECKSUM

      - name: Verify tarball
        run: sha256sum -c *-CHECKSUM --ignore-missing

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load the upstream Container image
        run: docker tag $(docker load --input ./${{ env.UPSTREAM_IMAGE }} | cut -d' ' -f3) localhost/fedora36:upstream

      - name: Build the Container image
        run: docker build ./fedora/ --file ./fedora/Dockerfile.fedora36-${{ matrix.type }} --tag ${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}"
          acs-report-enable: true
          fail-build: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
       
      - name: Push the container
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}
 
  build-scan-push-image:
    runs-on: ubuntu-latest
    needs: [build-scan-push-base-image]
    strategy:
      fail-fast: false
      matrix:
        type:
          - init
          - minimal
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container image
        run: docker build ./fedora/ --file ./fedora/Dockerfile.fedora36-${{ matrix.type }} --tag ${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}"
          acs-report-enable: true
          fail-build: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Push the container image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/fedora36-${{ matrix.type }}:${{ github.run_id }}
