name: Fedora Ansible image workflow

on:
  push:
    branches:
      - master
    paths:
      - 'fedora/**'
      - 'helper_scripts/buildah_multiarch.sh'
      - '.github/workflows/fedora-ansible_workflow.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'fedora/**'
      - 'helper_scripts/buildah_multiarch.sh'
      - '.github/workflows/fedora-ansible_workflow.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build-push-ansible-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Checkout deamen/ansible repo
        uses: actions/checkout@v5
        with:
          repository: deamen/ansible
          token: ${{ secrets.ANSIBLE_CIFS_PAT }}
          path: ansible
          ref: master

      - name: Setup buildah
        uses: deamen/gh-actions/setup-buildah@master
        with:
          os: 'ubuntu'

      - name: Build Fedora ansible image for amd64
        run: |
          ARCH=amd64 ./fedora/buildah_fedora-ansible.sh

      - name: Build Fedora ansible image for arm64
        run: |
          ARCH=arm64 ./fedora/buildah_fedora-ansible.sh

      - name: Log in to the Container registry with buildah
        run: |
          buildah login \
          --username ${{ vars.REGISTRY_USERNAME }} \
          --password ${{ secrets.REGISTRY_PASSWORD }} \
          ${{ vars.REGISTRY_SERVER }}

      - name: Create and push multi-arch manifest for ansible image
        run: |
          ./helper_scripts/buildah_multiarch.sh quay.io/deamen/fedora-ansible
