# This is a basic workflow to help you get started with Actions

name: "CIFS: fedora36"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: 
       - 'fedora36/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-fedora36-base-image:
    uses: ./.github/workflows/fedora_base_workflow.yml
    with:
      distro: fedora36
      registry: ghcr.io
      tarball: "Fedora-Container-Minimal-Base-36-1.5.x86_64.tar.xz"
      tarball_uri: "https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Container/x86_64/images"
      tarball_checksum_uri: "https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Container/x86_64/images"
      tarball_checksum_file: "Fedora-Container-36-1.5-x86_64-CHECKSUM"
      tarball_gpg_key: "fedora.gpg"
      tarball_gpg_uri: "https://getfedora.org/static"
 
  build-fedora36-init-and-minimal-image:
    needs: [build-fedora36-base-image]
    uses: ./.github/workflows/cifs_non_base_workflow.yml
    with:
      distro: fedora36
      registry: ghcr.io
