name: "CIFS: coss9-freeipa"

on:
  push:
    branches: [ "master" ]
    paths: 
       - 'coss9/**'
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-coss9-freeipa-image:
    runs-on: ubuntu-latest

    env:
      distro: coss9
      app: freeipa
      app_repo: freeipa/freeipa-container
      dockerfile: Dockerfile.centos-9-stream
      registry: ghcr.io

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
        with:
          repository: ${{ env.app_repo }}
          path: ${{ env.app  }}

      - name: Use coss9-init as base image
        run: sed -i 's/^FROM.*/FROM\ ghcr.io\/deamen\/cifs\/coss9-init:latest/g' ./${{ env.app_repo }}/${{ env.dockerfile  }}

      - name: Build the ${{ env.distro  }}-${{ env.app  }} image
        run: docker build ./${{ env.app  }} --file ./${{ env.app  }}/${{ env.dockerfile  }} --tag ${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:${{ github.run_id }} --tag ${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:latest

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the Anchore scan
        uses: anchore/scan-action@ecfd0e98932e57ea8f68f29c4f418fc41a8194db #v3.2.5
        with:
          image: "${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:${{ github.run_id }}"
          acs-report-enable: true
          fail-build: false

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 #v2.1.16
        with:
          sarif_file: results.sarif

      - name: Push the image
        run: docker push --all-tags ${{ env.registry }}/${{ github.repository }}/${{ env.distro }}-${{ env.app }}
