name: "CIFS: coss9-freeIPA"

on:
  push:
    branches: [ "master" ]
    paths: 
       - 'coss9/**'
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-coss9-base-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    env:
      distro: coss9
      app: freeipa
      app_repo: freeipa/freeipa-container
      dockerfile: Dockerfile.centos-9-stream
      registry: ghcr.io

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
        with:
          repository: ${{ env.app_repo }}

      - name: Use coss9-init as base image
        run: sed -i 's/^FROM.*/FROM\ ghcr.io\/deamen\/cifs\/coss9-init:latest/g' ./${{ env.dockerfile  }}

      - name: Build the ${{ env.distro  }}-${{ env.app  }} image
        run: docker build . --file ./${{ env.dockerfile  }} --tag ${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:${{ github.run_id }} --tag ${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:latest

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "${{ env.registry }}/${{ github.repository }}/${{ env.distro  }}-${{ env.app }}:${{ github.run_id }}"
          acs-report-enable: true
          fail-build: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Push the image
        run: docker push --all-tags ${{ env.registry }}/${{ github.repository }}/${{ env.distro }}-${{ env.app }}
