name: "CIFS: rocky8"

on:
  push:
    branches: [ "master" ]
    paths: 
       - 'rocky8/**'
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-rocky8-base-image:
    uses: ./.github/workflows/cifs_base_workflow.yml
    with:
      distro: rocky8
      registry: ghcr.io

  build-rocky8-init-and-minimal-image:
    needs: [build-rocky8-base-image]
    uses: ./.github/workflows/cifs_non_base_workflow.yml
    with:
      distro: rocky8
      registry: ghcr.io
